export const GUNS = {
  RIFLE: "rifle",
  SHOTGUN: "shotgun",
  SNIPER: "sniper",
};

export const GUN_SPECS = {
  rifle: {
    name: "Assault Rifle",
    magazine: 24,
    ammo: 120,
    fireRate: 0.074,
    reloadTime: 1.05,
    adsFov: 68,
    adsInSpeed: 11.5,
    adsOutSpeed: 8.5,
    adsMovePenalty: 0.14,
    damage: 34.5,
    pellets: 1,
    spread: 0,
    tracerLen: 1.75,
    tracerLife: 0.032,
    recoil: { kick: 42, kickDamping: 21, yaw: 76, yawDamping: 24, roll: 64, rollDamping: 22 },
  },
  shotgun: {
    name: "Combat Shotgun",
    magazine: 10,
    ammo: 80,
    fireRate: 0.34,
    reloadTime: 1.45,
    adsFov: 72,
    adsInSpeed: 10.5,
    adsOutSpeed: 7.5,
    adsMovePenalty: 0.12,
    damage: 195,
    pellets: 14,
    spread: 0.068,
    tracerLen: 1.05,
    tracerLife: 0.028,
    recoil: { kick: 96, kickDamping: 14, yaw: 112, yawDamping: 18, roll: 98, rollDamping: 16 },
  },
  sniper: {
    name: "Precision Rifle",
    magazine: 6,
    ammo: 30,
    fireRate: 1.05,
    reloadTime: 1.55,
    adsFov: 18,
    adsInSpeed: 8.4,
    adsOutSpeed: 7.0,
    adsMovePenalty: 0.2,
    damage: 205.54,
    pellets: 1,
    spread: 0.004,
    tracerLen: 2.85,
    tracerLife: 0.045,
    recoil: { kick: 64, kickDamping: 18, yaw: 145, yawDamping: 20, roll: 88, rollDamping: 19 },
  },
};

export function createGunState(gunType = GUNS.RIFLE) {
  const spec = GUN_SPECS[gunType];
  return {
    type: gunType,
    mag: spec.magazine,
    ammo: spec.ammo,
    magSize: spec.magazine,
    fireRate: spec.fireRate,
    fireCooldown: 0,
    reloadTime: spec.reloadTime,
    reloadTimer: 0,
    muzzleTimer: 0,
    damage: spec.damage,
    pellets: spec.pellets,
    spread: spec.spread,
    isAutoReloading: false,
    displayName: spec.name,
  };
}
